### ISSUE TITLE
Recursion error in dendrogram

### ISSUE THREAD

**Issue by CGUTA** [MaayanLab/clustergrammer-py#10]
Hello, I found out about clustergrammer through the jupytercon and I think is very cool.

I tried making the cluster from a dataset (17K genes 10K samples), but during the dendrogram construction an error occurs:

...scipy/cluster/hierarchy.py", line 2534, in _append_singleton_leaf_node
RecursionError: maximum recursion depth exceeded while getting the str of an object

Is there a way to deactivate the dendrogram to bypas this ?

**Comment by cornhundred** [comment]
We're glad you like Clustergrammer. For a dataset of that size I would recommend trying the new in-development [Clustergrammer-GL](https://github.com/ismms-himc/clustergrammer-gl) and [Clustergrammer2](https://github.com/ismms-himc/clustergrammer2) Jupyter widget - these are built using WebGL which allows visualization of larger datasets. However, I would also recommend reducing the dimensionality (try reducing to ~1,000) and randomly subsampling or downsampling your samples (try reding to 1,000 - 5,000). This will probably ifx the maximum recursion depth exceeded problem and you will be able to visualize the reduced size dataset. 

You can try out Clustergrammer2 on MyBinder on the CCLE dataset (18,000 genes and 1,000 cell-lines) to get an idea of how to visualize a similar dataset:

[![badge](https://img.shields.io/badge/launch-2.0%20CCLE%20Gene%20Expression-579ACA.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFkAAABZCAMAAABi1XidAAAB8lBMVEX///9XmsrmZYH1olJXmsr1olJXmsrmZYH1olJXmsr1olJXmsrmZYH1olL1olJXmsr1olJXmsrmZYH1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olJXmsrmZYH1olL1olL0nFf1olJXmsrmZYH1olJXmsq8dZb1olJXmsrmZYH1olJXmspXmspXmsr1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olLeaIVXmsrmZYH1olL1olL1olJXmsrmZYH1olLna31Xmsr1olJXmsr1olJXmsrmZYH1olLqoVr1olJXmsr1olJXmsrmZYH1olL1olKkfaPobXvviGabgadXmsqThKuofKHmZ4Dobnr1olJXmsr1olJXmspXmsr1olJXmsrfZ4TuhWn1olL1olJXmsqBi7X1olJXmspZmslbmMhbmsdemsVfl8ZgmsNim8Jpk8F0m7R4m7F5nLB6jbh7jbiDirOEibOGnKaMhq+PnaCVg6qWg6qegKaff6WhnpKofKGtnomxeZy3noG6dZi+n3vCcpPDcpPGn3bLb4/Mb47UbIrVa4rYoGjdaIbeaIXhoWHmZYHobXvpcHjqdHXreHLroVrsfG/uhGnuh2bwj2Hxk17yl1vzmljzm1j0nlX1olL3AJXWAAAAbXRSTlMAEBAQHx8gICAuLjAwMDw9PUBAQEpQUFBXV1hgYGBkcHBwcXl8gICAgoiIkJCQlJicnJ2goKCmqK+wsLC4usDAwMjP0NDQ1NbW3Nzg4ODi5+3v8PDw8/T09PX29vb39/f5+fr7+/z8/Pz9/v7+zczCxgAABC5JREFUeAHN1ul3k0UUBvCb1CTVpmpaitAGSLSpSuKCLWpbTKNJFGlcSMAFF63iUmRccNG6gLbuxkXU66JAUef/9LSpmXnyLr3T5AO/rzl5zj137p136BISy44fKJXuGN/d19PUfYeO67Znqtf2KH33Id1psXoFdW30sPZ1sMvs2D060AHqws4FHeJojLZqnw53cmfvg+XR8mC0OEjuxrXEkX5ydeVJLVIlV0e10PXk5k7dYeHu7Cj1j+49uKg7uLU61tGLw1lq27ugQYlclHC4bgv7VQ+TAyj5Zc/UjsPvs1sd5cWryWObtvWT2EPa4rtnWW3JkpjggEpbOsPr7F7EyNewtpBIslA7p43HCsnwooXTEc3UmPmCNn5lrqTJxy6nRmcavGZVt/3Da2pD5NHvsOHJCrdc1G2r3DITpU7yic7w/7Rxnjc0kt5GC4djiv2Sz3Fb2iEZg41/ddsFDoyuYrIkmFehz0HR2thPgQqMyQYb2OtB0WxsZ3BeG3+wpRb1vzl2UYBog8FfGhttFKjtAclnZYrRo9ryG9uG/FZQU4AEg8ZE9LjGMzTmqKXPLnlWVnIlQQTvxJf8ip7VgjZjyVPrjw1te5otM7RmP7xm+sK2Gv9I8Gi++BRbEkR9EBw8zRUcKxwp73xkaLiqQb+kGduJTNHG72zcW9LoJgqQxpP3/Tj//c3yB0tqzaml05/+orHLksVO+95kX7/7qgJvnjlrfr2Ggsyx0eoy9uPzN5SPd86aXggOsEKW2Prz7du3VID3/tzs/sSRs2w7ovVHKtjrX2pd7ZMlTxAYfBAL9jiDwfLkq55Tm7ifhMlTGPyCAs7RFRhn47JnlcB9RM5T97ASuZXIcVNuUDIndpDbdsfrqsOppeXl5Y+XVKdjFCTh+zGaVuj0d9zy05PPK3QzBamxdwtTCrzyg/2Rvf2EstUjordGwa/kx9mSJLr8mLLtCW8HHGJc2R5hS219IiF6PnTusOqcMl57gm0Z8kanKMAQg0qSyuZfn7zItsbGyO9QlnxY0eCuD1XL2ys/MsrQhltE7Ug0uFOzufJFE2PxBo/YAx8XPPdDwWN0MrDRYIZF0mSMKCNHgaIVFoBbNoLJ7tEQDKxGF0kcLQimojCZopv0OkNOyWCCg9XMVAi7ARJzQdM2QUh0gmBozjc3Skg6dSBRqDGYSUOu66Zg+I2fNZs/M3/f/Grl/XnyF1Gw3VKCez0PN5IUfFLqvgUN4C0qNqYs5YhPL+aVZYDE4IpUk57oSFnJm4FyCqqOE0jhY2SMyLFoo56zyo6becOS5UVDdj7Vih0zp+tcMhwRpBeLyqtIjlJKAIZSbI8SGSF3k0pA3mR5tHuwPFoa7N7reoq2bqCsAk1HqCu5uvI1n6JuRXI+S1Mco54YmYTwcn6Aeic+kssXi8XpXC4V3t7/ADuTNKaQJdScAAAAAElFTkSuQmCC)](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_examples/master?filepath=notebooks%2F2.0_CCLE_Gene_Expression.ipynb)

Also, see [clustergrammer2-examples](https://github.com/ismms-himc/clustergrammer2-examples) for more examples.

**Comment by CGUTA** [comment]
Thank you for your response,

I tried generating a JSON from a 10X10 mtx using clustergrammer-py and then plug it into the index.html of the clustergrammer-gl repo. But nothing renders (is the JSON from clustergrammer the same format for the clustergrammer-gl?). I checked the console and I get

```
clustergrammer-gl.js:39333 Uncaught TypeError: tmp_cat.indexOf is not a function
    at clustergrammer-gl.js:39333
    at Function.Clustergrammer2../node_modules/underscore/underscore.js._.each._.forEach (clustergrammer-gl.js:35794)
    at generate_cat_array (clustergrammer-gl.js:39323)
    at generate_cat_params (clustergrammer-gl.js:44770)
    at initialize_params (clustergrammer-gl.js:45146)
    at run_viz (clustergrammer-gl.js:42112)
    at clustergrammer_gl (clustergrammer-gl.js:43142)
    at (index):72
    at d3.js:2010
    at Object.<anonymous> (d3.js:1995)
```

the mtx that i used to generate the JSON is
```
		S1	S2	S3	S4	S5	S6	S7	S8	S9	S10	S11	S12
		3	3	3	3	3	3	4	3	3	3	3	3
Z	3	0	20	20	20	40	60	60	60	100	120	120	120
A	1	20	0	20	20	60	80	80	80	120	140	140	140
B	1	20	20	0	20	60	80	80	80	120	140	140	140
C	1	20	20	20	0	60	80	80	80	120	140	140	140
D	2	40	60	60	60	0	20	20	20	60	80	80	80
E	2	60	80	80	80	20	0	20	20	40	60	60	60
F	2	60	80	80	80	20	20	0	20	60	80	80	80
G	2	60	80	80	80	20	20	20	0	60	80	80	80
H	1	100	120	120	120	60	40	60	60	0	20	20	20
I	1	120	140	140	140	80	60	80	80	20	0	20	20
J	1	120	140	140	140	80	60	80	80	20	20	0	20
K	1	120	140	140	140	80	60	80	80	20	20	20	0
```

**Comment by CGUTA** [comment]
It worked!, I now generated the JSON directly for the clustergrammer GL. What I learned from the current build so far. 

- It expects groups and it expects categories. 
- ini refers to the ordering in the data, clust and rank's refer to cluster and other toggable orderings.
- the cat index are a mystery to me.
- all indexes are 1based except ini and cat_index(0based).

The error before was probably that the JSON from clustergrammer-py only works when it generates categories together with the dendrogram that are compatible with your current example mult_view.json in data.

**Comment by cornhundred** [comment]
Great, the cat_index is the order of the row/col when ordering by category (e.g. when double-clicking on the category title). For Clustergrammer-GL this is only currently working for column reordering, but soon I'll update to have row category reordering also.
