### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix' while trying to reproduce the Python workflow example

### ISSUE THREAD

**Issue by andrew-silvernail** [MaayanLab/clustergrammer-py#15]
**AttributeError: 'DataFrame' object has no attribute 'ix'**
clustergrammer.run_filter.grab_df_subset() calls the deprecated .ix() method on a dataframe in pandas.

**To Reproduce**
1. Create a virtualenv for clustergrammer
2. Install with `pip3 install clustergrammer`
3. Install the latest pandas `pip3 install pandas`
4. Grab an example matrix file from: https://github.com/MaayanLab/clustergrammer/tree/master/txt.
5. Copy-and-paste a workflow example from here: https://clustergrammer.readthedocs.io/clustergrammer_py.html#python-workflow-examples and change it to reference the file downloaded from step #3.

**Expected behavior**
A json file should be created.

**Desktop:**
 - OS: MacOS Mojave 10.14.6
 - Python v3.7.7

**Comment by cornhundred** [comment]
Hi @andrew-silvernail, thanks for raising the issue. We have fixed this issue in the new Clustergrammer2 library https://github.com/ismms-himc/clustergrammer2

We will make the same fix here soon, but we recommend users switch to Clustergrammer2 since it is being actively developed.

**Comment by andrew-silvernail** [comment]
> Hi @andrew-silvernail, thanks for raising the issue. We have fixed this issue in the new Clustergrammer2 library https://github.com/ismms-himc/clustergrammer2
> 
> We will make the same fix here soon, but we recommend users switch to Clustergrammer2 since it is being actively developed.

I discovered the new library shortly after posting this.  Thanks @cornhundred for the prompt reply.
